workflow:
  rules:
    # allow to publish a package from the Gitlab UI, on upgrade branch
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    # disable pipeline when pushing on master (when running release scripts)
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - when: always

.base:
  image: registry.caas.olympe.io/infra/docker/node-tools-light:stable
  tags: [eks]

# Initialize the npm environment with gitlab registry
.npm-config:
  extends: .base
  variables:
    VAULT_ADDR: https://vault.olympe.io
    VAULT_AUTH_ROLE: gitlab-ci
  before_script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_AUTH_ROLE} jwt=$CI_JOB_JWT)"
    - export NPM_TOKEN=$(vault kv get -field token kv/devops/npm/token)
    # Setup token for private npm registry
    - npm config set '//gitlab.caas.olympe.io/api/v4/projects/236/packages/npm/:_authToken' "$NPM_TOKEN"

stages:
  - setup
  - build
  - unit-tests
  - publish-lib

# Initialize the npm environment and install packages
setup:
  stage: setup
  extends: .npm-config
  script:
    - npm install
  artifacts:
    expire_in: 1 week
    paths:
      - node_modules/

# Build npm package
build-package:
  stage: build
  extends: .base
  dependencies:
    - setup
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then apt-get install -y jq; sh ./bumpVersion.sh; fi
    - npm run build;
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

# Run unit tests
tests:
  stage: unit-tests
  extends: .base
  dependencies:
    - setup
  # Use an image that includes chromium and jre for test
  image: registry.caas.olympe.io/infra/docker/node-tools:stable
  script:
    - npm test

# publish
#  - a package tagged "dev" when pushing on develop
#  - a package tagged "upgrade" upon manual trigger from Gitlab CI on upgrade (see workflow rules)
#  - in all other cases, publishing is skipped
publish:
  stage: publish-lib
  extends: .npm-config
  dependencies:
    - build-package
  script:
    - cd dist
    - NPM_PUBLISH_TAG="$CI_COMMIT_BRANCH"
    - if [ "$CI_COMMIT_BRANCH" == "upgrade" ]; then NPM_PUBLISH_TAG="upgrade"; fi
    - if [ "$CI_COMMIT_BRANCH" == "develop" ]; then NPM_PUBLISH_TAG="dev"; fi
    - npm publish --tag "$NPM_PUBLISH_TAG"
  rules:
    - if: $CI_COMMIT_TAG # publish of released version in private registry is managed by /olympeio/extensions/npm-registry scripts
      when: never
    - if: '($CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push") || $CI_COMMIT_BRANCH == "upgrade"'
      when: on_success

# Publish to public npm registry (npmjs.org). Publish only if a new version tag vX.Y.Z was pushed.
publish-public:
  stage: publish-lib
  dependencies:
    - build-package
  image: node:lts-bullseye-slim # Original node image to keep the public registry npmjs.org
  tags:
    - eks
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "$NPM_TOKEN"
    - cd dist
    - npm publish --access public
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
