variables:
  CHROME_BIN: "/usr/bin/chromium"

.image-init: &image-init
  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$GITLAB_SSH_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

.npm:
  image:
    name: registry.caas.olympe.cloud/infra/docker/node-tools:14-bullseye-slim
    entrypoint: [""]
  tags:
    - aws-spot-runner
  before_script:
    - *image-init
    - npm config set @olympeio:registry https://gitlab.caas.olympe.cloud/api/v4/projects/236/packages/npm/
    - npm config set '//gitlab.caas.olympe.cloud/api/v4/projects/236/packages/npm/:_authToken' "$GITLAB_TOKEN"

# Extra npm configuration to access to public npm registry (npmjs.org)
.npm-public:
  extends: .npm
  before_script:
    - *image-init
    - npm config set '//registry.npmjs.org/:_authToken' "$NPM_TOKEN"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

stages:
  - setup
  - build
  - unit-tests
  - deploy-app

setup:
  stage: setup
  extends: .npm
  script:
    - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
    
# Build npm package
build-package:
  stage: build
  extends: .npm
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then sh ./bumpVersion.sh; fi
    - npm run build
  dependencies:
    - setup
  artifacts:
    paths:
      - dist/

tests:
  stage: unit-tests
  extends: .npm
  script:
    - npm test

# Publish job
.publish:
  stage: deploy-app
  dependencies:
    - setup
    - build-package

# Publish to internal npm registry on gitlab
publish-internal:
  extends:
    - .npm
    - .publish
  script:
    # Set the tag to use for the newly published package :
    # - "dev" is used when commit comes from develop
    # - "stable" is used when we do a release
    # - "uat" is used when beta or rc tag is created
    - if [[ -z "$CI_COMMIT_TAG" ]]; then export TAG="dev"; elif [[ ${CI_COMMIT_TAG} =~ '(-rc|-beta)[0-9]+' ]]; then export TAG="uat"; else export TAG="stable"; fi
    - cd dist
    - npm publish --tag $TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(?:-(?:rc|beta)\.?\d+)?$/'

# Publish to public npm registry (npmjs.org). Publish only if a new version tag vX.Y.Z was pushed.
publish-public:
  extends:
    - .npm-public
    - .publish
  script:
    - cd dist
    - npm publish --access public
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
