variables:
  CHROME_BIN: "/usr/bin/chromium"

.npm:
  image:
    name: registry.caas.olympe.cloud/infra/docker/ci-unit-test-front:1.0.3
    entrypoint: [""]
  tags:
    - aws-spot-runner
  before_script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$GITLAB_SSH_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - npm config set @olympeio:registry https://gitlab.caas.olympe.cloud/api/v4/projects/236/packages/npm/
    - npm config set '//gitlab.caas.olympe.cloud/api/v4/projects/236/packages/npm/:_authToken' "$NPM_TOKEN"
    - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" npm install --cache .npm --prefer-offline

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

stages:
  - build
  - unit-tests
  - deploy-app

build-draw:
  stage: build
  extends: .npm
  script:
    - npm run build:draw
    - (cd dist && zip -r - .) > OLYMPE-DRAW-composer-ci-SNAPSHOT.zip
  artifacts:
    paths:
      - OLYMPE-DRAW-composer-ci-SNAPSHOT.zip

tests:
  stage: unit-tests
  extends: .npm
  script:
    - npm test

deploy-s3:
  stage: deploy-app
  image:
    name: banst/awscli
    entrypoint: [""]
  tags:
    - aws-spot-runner
  script:
    - aws s3 --endpoint-url https://sos-ch-gva-2.exo.io cp OLYMPE-DRAW-composer-ci-SNAPSHOT.zip s3://olympe-repository/releases/OLYMPE-DRAW/OLYMPE-DRAW-composer-ci-SNAPSHOT.zip
  dependencies:
    - build-draw

publish:
  stage: deploy-app
  extends: .npm
  script:
    - npm run build:lib
    - cd dist
    - npm publish
  rules:
    # - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(?:-(?:rc|beta)\.?\d+)?$/'
