repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: insert-license
        files: (src/|tests/)
        args:
          - --license-filepath
          - LICENSE_notice
          - --comment-style
          - /**| *| */
          - --detect-license-in-X-top-lines=15 # the license is 15 lines long with multiline comments
