# start backend apps
version: "3.3"
services:
  neo4j:
    image: "olympeio/neo4j-procedure:1.8.1"
    container_name: "neo4j"
    environment:
      NEO4J_AUTH: "neo4j/password1"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      # Offer neo4j console for debugging
      - 7474:7474
      - 7687:7687
    volumes:
      - ./backend/neo4j-data:/data
      - ./backend/neo4j-logs:/log
  orchestrator:
    image: "olympeio/orchestrator:5.8.3"
    depends_on:
      - neo4j
    container_name: "orchestrator"
    environment:
      DB_HOSTNAME: neo4j
      DB_USER: neo4j
      DB_PASSWORD: password1
      WAIT_FOR_NEO4J: 120
    volumes:
      - ./backend/orchestrator-file-service:/opt/orchestrator/file-service
      - ./backend/orchestrator-logs:/opt/orchestrator/logs
