// WARNING ****************************************************************************
// This file is automatically generated. We recommend that you do not edit it manually.
// ************************************************************************************
// Import Olympe runtime
import 'olympe';

// Import project bricks (we use webpack-import-glob-loader to import all bricks)
import './core/**/*.js';
import './web/**/*.js';
