// WARNING ****************************************************************************
// This file is automatically generated. We recommend that you do not edit it manually.
// ************************************************************************************

// This file imports Olympe and project and dependencies bricks source code, so that Webpack can bundle everything together. 

// Import Olympe runtime or DRAW
import 'olympe';

// Import project bricks (we use webpack-import-glob-loader to import all bricks)
import './core/**/*.js';

// Import further dependencies bricks
